use axum::extract::Path;
use fastrace::collector::Config;
use fastrace::collector::ConsoleReporter;
use tracing_subscriber::layer::SubscriberExt;

#[tokio::main]
async fn main() {
    // Configure compactibility layer to collect spans generated by axum.
    tracing::subscriber::set_global_default(
        tracing_subscriber::Registry::default().with(fastrace_tracing::FastraceCompatLayer::new()),
    )
    .unwrap();

    // Configurate logging reporter.
    logforth::stderr().apply();

    // Configurate fastrace reporter.
    fastrace::set_reporter(ConsoleReporter, Config::default());

    let app = axum::Router::new()
        .route("/ping", axum::routing::get(ping))
        .route("/ping/{id}", axum::routing::get(ping_with_id))
        // Add a the FastraceLayer to routes.
        // The layer extracts trace context from incoming requests.
        .layer(fastrace_axum::FastraceLayer);

    let listener = tokio::net::TcpListener::bind("0.0.0.0:8080").await.unwrap();
    axum::serve(listener, app).await.unwrap();

    // Flush all remaining traces before the program exits.
    fastrace::flush();
}

#[fastrace::trace] // Trace individual handlers.
async fn ping() -> &'static str {
    "pong"
}

#[fastrace::trace]
async fn ping_with_id(Path(id): Path<String>) -> String {
    format!("pong: {}", id)
}
